# Generated by Django 5.0.4 on 2024-05-15 10:44

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_name', models.CharField(default='', max_length=70)),
                ('mentor_salary', models.PositiveIntegerField(default=0)),
                ('mentor_schedule_time', models.CharField(default='', max_length=50)),
                ('mentor_experience', models.CharField(default='', max_length=50)),
                ('mentor_speciality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.category')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='', max_length=70)),
                ('course_description', models.TextField(default='')),
                ('course_price', models.PositiveIntegerField(default=0)),
                ('course_category', models.CharField(default='', max_length=50)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.category')),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.mentor')),
            ],
            managers=[
                ('courseManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='category_tag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.tag'),
        ),
    ]
