# Generated by Django 5.0.4 on 2024-05-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_category',
        ),
        migrations.AddField(
            model_name='course',
            name='course_picture',
            field=models.ImageField(null=True, upload_to='course/'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentor_picture',
            field=models.ImageField(null=True, upload_to='mentor/'),
        ),
    ]
